### ISSUE TITLE
does not work without first line comment 'out:' with Compile Every Sass file set.

### ISSUE THREAD

**Issue by yoorek** [armin-pfaeffle/sass-autocompile#26]
When I don't have first line comment with output e.g. //out: main.css  and I save file I get 'Sass-Autocompile: Successfully compiled' but no CSS file is present EVEN if I have 'Compile file.. Every SASS file' option set.

**Comment by armin-pfaeffle** [comment]
Hey!

First, can you try this: close Atom, open terminal and execute:
```
apm rebuild-module-cache
```
Then retry saving a file. There was a bug in previous versions that leads to update problems. Now everything is fixed and after executing the command above you don't have to do that any more.

Another idea would be to check if there is a node-sass update?!

Are you sure, that no CSS file is written? Try to enable panel notification (see [Notification type](https://github.com/armin-pfaeffle/sass-autocompile#notification-type)) and click on the output fliename. Then it should be opened in Atom. What happens after the click?

**Comment by yoorek** [comment]
ok, I think I might know what was the problem (although I did cache rebuild and reinstall, so It is hard to know for sure). When you have no output option set (no compact, compressed, nested, expanded) you still get 'SASS-Autocompile: Successfully compiled' message even if there is NO OUTPUT written to file - it is misleading. I think you should warn if there is no output option set instead confirming output.

**Comment by armin-pfaeffle** [comment]
Well, you are right! Thanks for your report!

I published version 0.10.4 right now, which fixes that "bug"!
